### ISSUE TITLE
memory safe DMA

### ISSUE THREAD

**Issue by japaric** [rust-embedded/book#101]
Let's write down the requirements for memory safe DMA transfers so that people can experiment with DMA abstractions independently.

**Comment by korken89** [comment]
I will try to stay in the loop here as much as possible, I use DMA for everything and would very much like to follow this progress.

**Comment by japaric** [comment]
I ended making a PR to the embedonomicon instead of to the book so I'm going to close this issue in favor of rust-embedded/embedonomicon#36.
