### ISSUE TITLE
Jitter ?

### ISSUE THREAD

**Issue by flip111** [rust-embedded/book#160]
https://rust-embedded.github.io/book/concurrency/index.html

> which comes at a cost to overhead and interrupt latency and jitter.

I don't really understand what the consequences are from disabled interrupts. Is it not so that interrupts will just be ignored ? But latency indicates they will be delayed? And what about jitter?

**Comment by adamgreig** [comment]
I think explaining interrupt latency and jitter is out of scope for the book (and especially for the concurrency section); the introduction says we assume familiarity with interrupts in an embedded context.

> Is it not so that interrupts will just be ignored ? But latency indicates they will be delayed? And what about jitter?

When interrupt handling is disabled in a critical section, interrupts are left pending, and will be serviced once interrupt handling is re-enabled (hence the additional latency and jitter).
