### ISSUE TITLE
Picture broken

### ISSUE THREAD

**Issue by japaric** [rust-embedded/book#18]
See: https://rust-embedded.github.io/book/intro/hardware.html

The image link says https://rust-embedded.github.io/assets/f3.jpg ; it should be https://rust-embedded.github.io/book/assets/f3.jpg

**Comment by Caemor** [comment]
The links in https://rust-embedded.github.io/book/intro/install.html#os-specific-instructions are also broken.

Maybe it would be better to use relative paths like use `../assets/f3.jpg` everywhere.
Pro: You can see the img file directly on github 
Con: You would need to be careful where you move the markdown file to not break the relative links.
