### ISSUE TITLE
typo / grammar in first sentence of Static Guarantees section

### ISSUE THREAD

**Issue by tim-seoss** [rust-embedded/book#182]
I think this would probably be considered incorrect grammar in most dialects of English:

"It's Rust's type system what prevents data races at compile time (see Send and Sync traits)."

I'd suggest:

"Rust's type system prevents data races at compile time (see Send and Sync traits)."

or maybe

"It's Rust's type system that prevents data races at compile time (see Send and Sync traits)."

Otherwise can't fault the book yet, keep up the good work!

**Comment by adamgreig** [comment]
Thanks for catching this! Would you mind opening a PR to fix this and any other issues you spot?

**Comment by tim-seoss** [comment]
Fixed with PR #183
