### ISSUE TITLE
intro/install/verify.md grammatical error

### ISSUE THREAD

**Issue by nickgolangi** [rust-embedded/book#184]
https://rust-embedded.github.io/book/intro/install/verify.html, second to last paragraph

Error:

> If the commands do work with root permission then check that the udev rules **has** been correctly set.

Fix:

> If the commands do work with root permission then check that the udev rules **have** been correctly set.

**Comment by nickgolangi** [comment]
First person used in https://rust-embedded.github.io/book/start/qemu.html

> Let me break down that long QEMU command for you:

**Comment by therealprof** [comment]
@nickgolangi Thanks for noticing. Would you mind creating a pull request with your suggested fixes?

**Comment by nickgolangi** [comment]
Done in https://github.com/rust-embedded/book/pull/185.
