### ISSUE TITLE
Book does not specify how to install cargo-generate

### ISSUE THREAD

**Issue by LucianoMoretti** [rust-embedded/book#186]

**Comment by LucianoMoretti** [comment]
https://rust-embedded.github.io/book/intro/install.html does not specify that cargo-generate needs to be installed during the setup instructions.

**Comment by LucianoMoretti** [comment]
Also need OpenSSL dependency and how to install.

**Comment by stefaneicher** [comment]
Yes. Would be helpful if you could mention to run
"cargo install cargo-generate"
in https://docs.rust-embedded.org/book/start/qemu.html before  section "Using cargo-generate"

**Comment by therealprof** [comment]
I guess this would be a good opportunity to contribute such a change. 😉

**Comment by stefaneicher** [comment]
hei daniel, 
yes sure. I will do it. 
Gruss
