### ISSUE TITLE
Updated link for Windows OpenOCD download

### ISSUE THREAD

**Issue by gjf2a** [rust-embedded/book#217]
Hello, I just got started with the book on my Windows machine. The old OpenOCD link leads to something broken and deprecated. I found the following link much more useful in getting OpenOCD installed:

https://gnutoolchains.com/arm-eabi/openocd/

**Comment by blelem** [comment]
I also stumbled on that deprecated link.  

I used the openocd-xpack : https://github.com/xpack-dev-tools/openocd-xpack
It seems to work well, although it's installed pretty deep in AppData : C:\Users\XXX\AppData\Roaming\xPacks\@xpack-dev-tools\openocd\0.10.0-13.1\.content\bin
