### ISSUE TITLE
Including a Glossary

### ISSUE THREAD

**Issue by phansch** [rust-embedded/book#220]
I realize that this book is not targeted to embedded beginners. It would still be nice to have some place to look up common appreviations used in embedded development with a link to more details. Being able to just hit `s` instead of going to search would make things a lot easier. The [rustc-guide](https://rust-lang.github.io/rustc-guide/appendix/glossary.html#appendix-c-glossary) might be a good example.

Some abbreviations from the first few pages that are never explained in the book:

* I2C
* SPI
* USART
* FPU
* PAC

I would be happy to give this a start

**Comment by therealprof** [comment]
Hi @phansch, that's a phantastic idea! We'd be delighted to have that.
