### ISSUE TITLE
interface/stlink-v2-1.cfg is deprecated, please switch to interface/stlink.cfg

### ISSUE THREAD

**Issue by blelem** [rust-embedded/book#237]
In section 1.4.4, the proposed configuration seems to be deprecated by STM.
`openocd -f interface/stlink-v2-1.cfg -f target/stm32f3x.cfg`
since it generates a warning
`WARNING: interface/stlink-v2-1.cfg is deprecated, please switch to interface/stlink.cfg`
the cfg file proposed by openocd seems to work fine, so perhaps the book could be updated accordingly.
`openocd -f interface/stlink.cfg -f target/stm32f3x.cfg`

BTW, It took me about an hour to get through the introduction/installation chapter. Considering the amount of different SW components involved, that was a smooth ride! Thanks for writing this book!

**Comment by guswynn** [comment]
as far as I can tell, stlink.cfg does not yet exist on the homebrewed version of openocd on OSX, do you mind if I open a PR to add a note?
