### ISSUE TITLE
Add documentation for Cortex-M23/M33/M35P

### ISSUE THREAD

**Issue by NZSmartie** [rust-embedded/book#262]
_This is sort of a cross-posted issue from https://github.com/rust-embedded/cortex-m-quickstart/issues/94_

I'm getting started with a `ATSAML10xxxx` series project that uses Cortex M23 (ARM v8 baseline)

Since I'm new to Rust development (but already an experienced embedded developer), I've been following [The Embedded Rust Book - Installing the tools](https://docs.rust-embedded.org/book/intro/install.html#installing-the-tools). Specifically it suggests adding the following targets with `rustup target add`

- `thumbv6m-none-eabi`
- `thumbv7m-none-eabi`
- `thumbv7em-none-eabi`
- `thumbv7em-none-eabihf`

As for ARM v8 baseline, mainline and mainline with extension, the targets are respectively:
- `thumbv8m.base-none-eabi` (e.g. Cortex M23)
- ` thumbv8m.main-none-eabi` (Not sure which arch uses this instruction set specifically 🤷‍♀️)
- `thumbv8m.main-none-eabihf`  (e.g. Cortex M33, CortexM35P)

Could these be added to `src/intro/install.md` and also other places I've yet to come across? 

https://github.com/rust-embedded/book/blob/0cd2ca116274b915924c3a7e07c1e046b6f19b77/src/intro/install.md#L14-L40

Maybe a reference to the [Cortex-M comparison table](https://developer.arm.com/ip-products/processors/cortex-m#c-7d3b69ce-5b17-4c9e-8f06-59b605713133) might help with picking out the right instruction set

**Comment by eldruin** [comment]
Sounds fine to me, although that list is getting longer. Could you send a PR to this repo adding these?
