### ISSUE TITLE
Book doesn't track .cargo/config -> .cargo/config.toml change in quickstart code

### ISSUE THREAD

**Issue by cleichner** [rust-embedded/book#295]
On [this page](https://docs.rust-embedded.org/book/start/qemu.html) there are several references to .cargo/config, https://github.com/rust-embedded/cortex-m-quickstart/commit/67b9c7c404b02ffe804c6f4c5600a21ca3a4502e recently changed the name of those files so the book examples lead to errors.

**Comment by adamgreig** [comment]
Thanks for reporting this, good catch! Would you be interested in making a PR to fix it in the book?

**Comment by cleichner** [comment]
Done. https://github.com/rust-embedded/book/pull/296

**Comment by adamgreig** [comment]
Closed by #296, thanks!
