### ISSUE TITLE
Installation of cargo-generate on Ubuntu fails owing to missing OS packages

### ISSUE THREAD

**Issue by rod-chapman** [rust-embedded/book#302]
I am trying to follow the installation instructions in section 1.4 on a stock Ubuntu Beaver installation.

The "cargo install cargo-generate" command fails owing to missing OS packages "libssl-dev" and "pkg-config".

I had to do "sudo apt install libssl-dev pkg-config" before it would work, so this should probably be mentioned in section 1.4 somewhere.

**Comment by eldruin** [comment]
Good catch. Could you open a PR adding this information?

**Comment by rod-chapman** [comment]
I'm not sure... Section 1.4 is supposed to be OS independent, with Linux-specific stuff following in section 1.4.1, so perhaps these sections need to be re-ordered a bit? I'm not confident enough to make such a change. Who has editorial/review control over this section?

**Comment by rod-chapman** [comment]
Do I need to fork this repo first, then propose a PR from there?

**Comment by rod-chapman** [comment]
OK.. I will give it a go...
