### ISSUE TITLE
Small sections about performing math functionality

### ISSUE THREAD

**Issue by robamu** [rust-embedded/book#306]
Correct me if I am missing any information, but I was not able to use some standard float operations like `floor` and `ceil` and I required those when calculating register values for a HAL. Am I missing a necessary import for this? I now added the `libm` dependency and was able to use the `floorf` functions for my purposes, but I think not being able to use functions like `floor` is related to having the `#[no_std]`  attribute on the application?

If that is the case, it might be worth an idea to add a small section related to how to perform some basic math operations which are reserved to `std` normally

**Comment by eldruin** [comment]
That is correct. It would be great if you could contribute that small section about this in a PR.

**Comment by robamu** [comment]
Unfortunately, I'm not an expert (yet), I only stumbled upon this when trying to do floating point calculation on a MCU. I could try to get some information about which math operations are allowed and which ones are reserved to `std` . I might do some research. Maybe someone already compiled a list or something similar? Then I could try to contribute a small section about this topic.

**Comment by robamu** [comment]
A related RFC can be found here: https://github.com/rust-lang/rfcs/issues/2505
