### ISSUE TITLE
Interoperability: On the availability of `std::ffi` and `std::os::raw` in `core`

### ISSUE THREAD

**Issue by abt8601** [rust-embedded/book#348]
The [section on interoperability](https://doc.rust-lang.org/stable/embedded-book/interoperability/index.html) mentions that "Neither of these modules [`std::ffi` and `std::os::raw`] are available in `core`". Nonetheless, `core::ffi` has been around since Rust 1.30 and, to my knowledge, contains almost everything that `std::ffi` and `std::os::raw` has to offer.

Moreover, since the documentation of `std::os::raw` explicitly states, "Use `core::ffi` instead" and that `std::ffi` contains everything that `std::os::raw` has, we should probably remove mentions of `std::os::raw`.

**Comment by eldruin** [comment]
Sounds reasonable. Please feel free to open a PR updating the section.
