### ISSUE TITLE
Links to other resources

### ISSUE THREAD

**Issue by mgeisler** [rust-embedded/book#353]
Hi there,

I maintain [Comprehensive Rust 🦀](https://google.github.io/comprehensive-rust/) and we've recently added a full day about [Bare-metal Rust](https://google.github.io/comprehensive-rust/bare-metal.html).

Would there be interest in having a section in your book with links to other resources, such as this course?

I created [such a page](https://google.github.io/comprehensive-rust/other-resources.html) for my course and I've found it very helpful since it gives me something to point students to when they want to learn more.

**Comment by eldruin** [comment]
Hi, that would definitely be welcome here.
Would you mind opening a PR?

**Comment by mgeisler** [comment]
Thanks @eldruin, I created #354 to add a link!
