### ISSUE TITLE
Use Rust 2018 syntax?

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/book#41]
Should we be using Rust 2018 syntax in the book? The main change would be removing `extern crate` statements.

**Comment by hyperslv** [comment]
agree but the suggested change has to be synchronized with the appropriate change in source code of the examples at github.com/rust-embedded/cortex-m-quickstart .
I will help & fix both if someone explains me how to synchronize these Repos

**Comment by therealprof** [comment]
What do you mean by synchronize? Open PRs on both and then we'll merge them, couldn't be easier. 😅

**Comment by hyperslv** [comment]
Created a [PR](https://github.com/rust-embedded/book/pull/248) on this issue

**Comment by hyperslv** [comment]
This issue might be closed since the appropriate [PR](https://github.com/rust-embedded/book/pull/248) was merged.

**Comment by Narukara** [comment]
There are still some `extern crate` statements in the book. For example:

https://github.com/rust-embedded/book/blob/19f798d448835a4888e3b3eae7fe69f1d61d8681/src/peripherals/singletons.md?plain=1#L65

https://github.com/rust-embedded/book/blob/09986cd352404eb4659db44613b27cac9aa652fc/src/collections/index.md?plain=1#L33

Shall we fix them all?

**Comment by eldruin** [comment]
@Narukara I would welcome a PR fixing them all. We could then close this issue.
