### ISSUE TITLE
Issue loading binary onto stm32f3discovery

### ISSUE THREAD

**Issue by Frederik-Baetens** [rust-embedded/book#43]
Hello, i tried to follow the guide in the rust book as well as possible, but i'm unable to load binaries on the microcontroller.

I already upgraded to the latest firmware with the tool from the st website.

This is what i'm doing in gdb: (i also ran monitor reset halt prior to this in gdb to make a "undefined debug reason 7 - target needs reset" error go away in openocd.)

```
~/Documents/programmeren/rust/micro/app : arm-none-eabi-gdb -q target/thumbv7em-none-eabihf/debug/examples/hello
Reading symbols from /home/frederik/Documents/programmeren/rust/micro/app/target/thumbv7em-none-eabihf/debug/examples/hello...done.
(gdb) target remote :3333
Remote debugging using :3333
0x08003cc8 in ?? ()
(gdb) load
Loading section .vector_table, size 0x400 lma 0x0
Loading section .text, size 0x2064 lma 0x400
Load failed
```

I'm sorry if this isn't the right place to post this.

**Comment by therealprof** [comment]
Just to make sure the issue is generally wrong instructions in the book I tried the instructions step-by-step and it does work for me:
```
# arm-none-eabi-gdb -q target/thumbv7em-none-eabihf/debug/examples/hello
Reading symbols from target/thumbv7em-none-eabihf/debug/examples/hello...done.
(gdb) target remote :3333
Remote debugging using :3333
Reset () at /Users/egger/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rt-0.6.4/src/lib.rs:494
494	    __pre_init();
(gdb) load
Loading section .vector_table, size 0x400 lma 0x8000000
Loading section .text, size 0x2032 lma 0x8000400
Loading section .rodata, size 0x604 lma 0x8002440
Start address 0x80021f4, load size 10806
Transfer rate: 15 KB/sec, 3602 bytes/write.
(gdb) target ext :3333
A program is being debugged already.  Kill it? (y or n) y
Remote debugging using :3333
Reset () at /Users/egger/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rt-0.6.4/src/lib.rs:494
494	    __pre_init();
(gdb) load
Loading section .vector_table, size 0x400 lma 0x8000000
Loading section .text, size 0x2032 lma 0x8000400
Loading section .rodata, size 0x604 lma 0x8002440
Start address 0x80021f4, load size 10806
Transfer rate: 15 KB/sec, 3602 bytes/write.
```

**Comment by Frederik-Baetens** [comment]
I configured my memory.x file wrong, and i was using the wrong gdb version, i needed the gdb for arm (arm-none-eabi-gdb). 

The "monitor reset halt" is also not necessary

**Comment by GregWoods** [comment]
i have the exact same issue. It appears the memory offsets in my memory.x are being ignored.
How exactly is memory.x used?
I don't specify it anywhere. Is it loaded by some convention?

memory.x is difficult to 'google', as the search engine assumes I want to know about the gdb 'x' command.

**Comment by thejpster** [comment]
It's copied in to your build output tree with build.rs, and included by the cortex-m-rt linker script, which is specified in the .cargo/config file.

**Comment by tafia** [comment]
> I configured my memory.x file wrong, and i was using the wrong gdb version, i needed the gdb for arm (arm-none-eabi-gdb).

Thanks! My memory.x was wrong too but I could use gdb-multiarch (ubuntu 18.04). I think I had to use `monitor reset halt` once.

Just for reference in case someone else comes here, here is the memory.x for my stm32f103c8t6:
```
MEMORY
{
  /* NOTE 1 K = 1 KiBi = 1024 bytes */
  FLASH : ORIGIN = 0x08000000, LENGTH = 128K
  RAM : ORIGIN = 0x20000000, LENGTH = 20K
}
```
