### ISSUE TITLE
Introduction - Link to repository is broken

### ISSUE THREAD

**Issue by klotzambein** [rust-embedded/book#50]
The link in the bottom links to https://github.com/rust-lang-nursery/embedded-wg/book, should probably link to https://github.com/rust-embedded/book.

**Comment by klotzambein** [comment]
The first link in this chapter: https://github.com/rust-embedded/book/blob/master/src/intro/introduction.md#contributing-to-this-book.

**Comment by therealprof** [comment]
Thanks for noticing. The link to the issue tracker was also wrong.
