### ISSUE TITLE
Installing dependencies for cortex-m-quickstart

### ISSUE THREAD

**Issue by drumbat** [rust-embedded/book#96]
Working through the book for the first time, cross compiling failed because I didn't have the `cortex-m-quickstart` dependencies installed.

It could be worthwhile including an extra step in the Getting Started/QEMU/Cross compiling section, namely to run: `rustup target add  thumbv7m-none-eabi`.

**Comment by adamgreen** [comment]
@drumbat Isn't this covered in the previous [Installation chapter](https://docs.rust-embedded.org/book/intro/install.html#rust-toolchain)?

**Comment by drumbat** [comment]
Yes it is, my apologies.
